export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_TOOL_TYPES = 'SET_TOOL_TYPES';
export const MODIFY_TOOL_TYPE = 'MODIFY_TOOL_TYPE';
export const REMOVE_TOOL_TYPE = 'REMOVE_TOOL_TYPE';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_COMPANIES = 'SET_COMPANIES';
export const MODIFY_COMPANY = 'MODIFY_COMPANY';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';
